import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import SideNav from "../components/Sidenav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {  
  return (
    <html lang="en">
      <body className={inter.className} >
      <div className="max-w-[1550px] mx-auto">
      <Header/>
      <div className="flex">
      <SideNav />
      <div>
      <div className="h-14" />
      {children}
      </div>
      </div>
      </div>
      </body>
    </html>
  );
}
